### ISSUE TITLE
1000-mforce-l32.patch for gcc-9.2.0 is missing

### ISSUE THREAD

**Issue by todork** [someburner/crosstool-ng#2]
### unrecognized command line option '-mforce-l32'

xtensa-lx106-elf-gcc: error: unrecognized command line option '-mforce-l32'
make[1]: *** [<builtin>: lwip/core/def.o] Error 1
default: make[1]: Leaving directory '/home/vagrant/esp-open-sdk/esp-open-lwip'

The compilation is ran on ubuntu-20.04 

This results later on the compilation of the micropython with the same error.

May be this patch could work
https://raw.githubusercontent.com/earlephilhower/esp-quick-toolchain/master/patches/gcc9.2/gcc-mforce-l32.patch
but I'm not an expert.

Regards,
Todor

Sorry, mistake!!!
This was directed to https://github.com/Phidelux/esp-open-sdk.git
Regards,
Todor

**Comment by someburner** [comment]
yeah I just haven't copied over the patches for 9.2.0. You just need to make a new folder for 9.2.0 and copy the patch there.

edit: actually my repo has this already
